config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :donors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :charges

  resources :partners, only: [:index, :show]

  resources :locations, only: [:index, :show] do
    authenticate :admin do
      resources :projects, only: [:new, :create, :edit, :update, :destroy] do
        resources :campaigns, only: [:new, :create, :edit, :update, :destroy]
      end
    end

    resources :projects, only: [:index, :show] do
      resources :campaigns, only: [:index, :show]
    end
  end

  authenticate :admin do
    resources :locations, only: [:new, :create, :edit, :update, :destroy]
    resources :partners, only: [:new, :create, :edit, :update, :destroy]
  end

  # start polymorphic address/addressableassociations
  resources :partners do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :projects do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :donors do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :admins do
    resources :addresses, only: [:new, :create, :edit, :update]
  end
  # end polymorphic address/addressable associations
end

app/models/partner.rb
class Partner < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  # must have a name and a slug
  validates_presence_of :name, :slug

  has_many :projects
  has_many :addresses, as: :addressable

  default_scope {order(name: :asc)}
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @partners = Partner.all
  end

  def show
    @partner = Partner.friendly.find(params[:id])
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)
    if @partner.save
      flash[:notice] = 'Created partner successfully'
      redirect_to partners_path
    else
      flash[:notice] = 'Save error, please try again'
      render :new
    end
  end

  def edit
    @partner = Partner.friendly.find(params[:id])
  end

  def update
    @partner = Partner.friendly.find(params[:id])
    if @partner.update_attributes(partner_params)
      flash[:notice] = 'Updated partner successfully'
      redirect_to partners_path
    else
      flash[:notice] = 'Save error, please try again'
      render :edit
    end
  end

  def destroy
    Partner.friendly.find(params[:id]).destroy
    flash[:success] = "Partner deleted"
    redirect_to partners_path
  end

  private
    def partner_params
      params.require(:partner).permit(:name, :slug, :logo_aws_url)
    end
end

app/views/partners/_form.html.erb
<%= form_for(partner) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :logo_aws_url %>
    <%= f.text_field :logo_aws_url, class: "form-control" %>
  </div>
  <%= f.submit 'Submit', class: "btn btn-default" %>
<% end %>

app/views/partners/edit.html.erb
<%= render partial: "form", locals: {partner: @partner} %>

app/views/partners/index.html.erb
<h1>Partners</h1>
<% if admin_signed_in? %>
  <% if @partners.present? %>
    <h2>partners</h2>
    <ul>
    <% @partners.each do |partner| %>
      <li><%= link_to partner.name, partner_path(partner) %>
          <%= link_to 'Edit', edit_partner_path(partner) %>
          <%= link_to 'Delete', partner, method: :delete,
              data: { confirm: "You want to delete this Partner?"} %>

          </li>
    <% end %>
    <ul>
  <% end %>
  <%= link_to 'Create partner', new_partner_path, class: 'btn btn-default' %>
<% else %>
  <% if @partners.present? %>
    <h2>Partners</h2>
    <ul>
    <% @partners.each do |partner| %>
      <li><%= link_to partner.name, partner_path(partner) %></li>
    <% end %>
    <ul>
  <% end %>
<% end %>

app/views/partners/new.html.erb
<%= render partial: "form", locals: {partner: @partner} %>

app/views/partners/show.html.erb
<h1>Partner</h1>

<p>
  <% if @partner.logo_aws_url.present? %>
    <img src="<%= @partner.logo_aws_url %>" alt="logo for <%= @partner.name %>">
  <% end %>
</p>


<% if @partner.addresses.last.present? %>
  <address>
    <p><%= @partner.addresses.last.street1 %></p>
    <% if @partner.addresses.last.street2.present? %>
      <p><%= @partner.addresses.last.street2 %></p>
    <% end %>
    <p><%= @partner.addresses.last.city %>, <%= @partner.addresses.last.state %> <%= @partner.addresses.last.zip %></p>
    <p><%= @partner.addresses.last.phone %></p>
    <p><%= @partner.addresses.last.email %></p>
    <p><%= @partner.addresses.last.homepage %></p>
  </address>
  <%= link_to 'Edit Address', edit_partner_address_path(@partner, @partner.addresses.last), class: 'btn btn-default' %>
<% else %>
  <% if admin_signed_in? %>
    <%= link_to 'Add Address?', new_partner_address_path(@partner), class: 'btn btn-default' %>
  <% else %>
    Address coming soon :\
  <% end %>
<% end %>


<h2>Projects</h2>
<% if @partner.projects.present? %>
  <% @partner.projects.each do |project| %>
    <%= link_to project.name, location_project_path(project.location, project) %>
    <% if admin_signed_in? %>
      <%= link_to 'Edit Project', edit_location_project_path(project.location, project) %>
      <%= link_to 'Delete Project', location_project_path(project.location, project), method: :delete, data: {confirm: "You sure you want to delete this project?"} %>
      <% if admin_signed_in? %>
        <%= link_to "Add new project in #{project.location.name}", new_location_project_path(project.location) %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <p>No Projects yet for <%= @partner.name %></p>
  <% if admin_signed_in? %>
    <%= link_to 'Add new project', new_project_path(@partner), class: 'btn btn-default' %>
  <% end %>
<% end %>