config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :donors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :charges

  resources :partners, only: [:index, :show]

  resources :locations, only: [:index, :show] do
    authenticate :admin do
      resources :projects, only: [:new, :create, :edit, :update, :destroy] do
        resources :campaigns, only: [:new, :create, :edit, :update, :destroy]
      end
    end

    resources :projects, only: [:index, :show] do
      resources :campaigns, only: [:index, :show]
    end
  end

  authenticate :admin do
    resources :locations, only: [:new, :create, :edit, :update, :destroy]
    resources :partners, only: [:new, :create, :edit, :update, :destroy]
  end

  # start polymorphic address/addressableassociations
  resources :partners do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :projects do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :donors do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :admins do
    resources :addresses, only: [:new, :create, :edit, :update]
  end
  # end polymorphic address/addressable associations
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @location = Location.first
    @locations = Location.all
    @partners = Partner.all
  end
end

app/views/home/index.html.erb
<h1>Climate Cents</h1>
<nav>
  <% if donor_signed_in? %>
    <ul>
      <li>Hello, <%= link_to current_donor.email, edit_donor_registration_path %></li>
      <li><%= link_to 'Log Out', destroy_donor_session_path, method: :delete %></li>
    </ul>
  <% elsif admin_signed_in? %>
    <ul>
      <li>Hello, admin <%= link_to current_admin.email, edit_admin_registration_path %></li>
      <li><%= link_to 'Log Out', destroy_donor_session_path, method: :delete %></li>
    </ul>
  <% else %>
    <ul>
      <li><%= link_to 'Sign Up', new_donor_registration_path %></li>
      <li><%= link_to 'Sign in', new_donor_session_path %></li>
    </ul>
  <% end %>
</nav>

<section>
  <%= link_to 'Locations', locations_path %>
  <% if @locations.present? %>
    <ul>
      <% @locations.each do |location| %>
        <li><%= link_to location.name, location_path(location) %></li>
      <% end %>
    </ul>
  <% end %>
</section>

<% if @partners.present? %>
  <%= link_to 'Partners', partners_path %>
  <ul>
  <% @partners.each do |partner| %>
    <li><%= link_to partner.name, partner_path(partner) %></li>
  <% end %>
  </ul>
<% end %>