config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :donors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :charges

  resources :partners, only: [:index, :show]

  resources :locations, only: [:index, :show] do
    authenticate :admin do
      resources :projects, only: [:new, :create, :edit, :update, :destroy] do
        resources :campaigns, only: [:new, :create, :edit, :update, :destroy]
      end
    end

    resources :projects, only: [:index, :show] do
      resources :campaigns, only: [:index, :show]
    end
  end

  authenticate :admin do
    resources :locations, only: [:new, :create, :edit, :update, :destroy]
    resources :partners, only: [:new, :create, :edit, :update, :destroy]
  end

  # start polymorphic address/addressableassociations
  resources :partners do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :projects do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :donors do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :admins do
    resources :addresses, only: [:new, :create, :edit, :update]
  end
  # end polymorphic address/addressable associations
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  # must have a unique name and a slug
  validates_presence_of :name, :slug
  validates_uniqueness_of :name, :slug

  belongs_to :partner
  belongs_to :location

  has_many :campaigns
  has_many :addresses, as: :addressable

  default_scope {order(name: :asc)}
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_location
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @projects = @location.projects.all
  end

  def show
    @project = @location.projects.friendly.find(params[:id])
  end

  def new
    @project = @location.projects.new
  end

  def create
    @project = @location.projects.build(project_params)
    if @project.save
      flash[:notice] = "Successfully created project."
      redirect_to location_projects_path
    else
      flash[:notice] = "Create error, please try again."
      render :new
    end
  end

  def edit
    @project = @location.projects.friendly.find(params[:id])
  end

  def update
    @project = @location.projects.friendly.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:notice] = 'Updated partner successfully'
      redirect_to location_projects_path
    else
      flash[:notice] = 'Save error, please try again'
      render :edit
    end
  end

  def destroy
    Project.friendly.find(params[:id]).destroy
    flash[:success] = "Project deleted"
    redirect_to location_projects_path
  end

  private
    def project_params
      params.require(:project).permit(:name, :slug, :blurb, :description,
        :location_id, :partner_id)
    end

    def find_location
      @location = Location.friendly.find(params[:location_id])
    end

end

app/views/projects/_form.html.erb
<%= form_for([location, project]) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :blurb %>
    <%= f.text_area :blurb, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :partner_id %>
    <%= f.collection_select :partner_id, Partner.all, :id, :name %>
  </div>

  <%= f.submit 'Submit', class: "btn btn-default" %>
<% end %>

app/views/projects/edit.html.erb
<%= render partial: "form", locals: { location: @location, project: @project } %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<% if @projects.present? %>
  <% @projects.each do |project| %>
    <h2><%= link_to project.name, location_project_path(@location, project) %></h2>
    <p><%= project.blurb %></p>
    <% if admin_signed_in? %>
      <%= link_to 'edit', edit_location_project_path(@location, project), class: "btn btn-default" %>
      <%= link_to 'delete', location_project_path(@location, project), method: :delete, class: 'btn btn-default', data: {confirm: "Are you sure you want to delete this project?"} %>
    <% end %>
  <% end %>
<% end %>

<% if admin_signed_in? %>
  <hr />
  <div>
    <%= link_to 'Create Project', new_location_project_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/projects/new.html.erb
<%= render partial: "form", locals: { location: @location, project: @project } %>

app/views/projects/show.html.erb
<h1>Project</h1>
<% if @project.present? %>
  <h2><%= @project.name %></h2>
  <p><%= @project.description %></p>
<% else %>
  <h2>No project found</h2>
<% end %>

<% if @project.campaigns.present? %>
  <h2>Project</h2>
  <ul>
    <% @project.campaigns.each do |campaign| %>
      <% if campaign.end_date > Time.now %>
        <h4><%= link_to campaign.name, location_project_campaign_path(@location, @project, campaign) %></h4>
        <%= form_tag charges_path do %>
          <article>
            <label class="amount">
              <span>Amount: $5.00</span>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="This is a test of $5 buy"
            data-amount="500">
          </script>
        <% end %>
       <% end %>
    <% end %>
  </ul>
<% end %>

<% if @project.addresses.last.present? %>
  <address>
    <p><%= @project.addresses.last.street1 %></p>
    <% if @project.addresses.last.street2.present? %>
      <p><%= @project.addresses.last.street2 %></p>
    <% end %>
    <p><%= @project.addresses.last.city %>, <%= @project.addresses.last.state %> <%= @project.addresses.last.zip %></p>
    <p><%= @project.addresses.last.phone %></p>
    <p><%= @project.addresses.last.email %></p>
    <p><%= @project.addresses.last.homepage %></p>
  </address>
  <%= link_to 'Edit Address', edit_partner_address_path(@project, @project.addresses.last), class: 'btn btn-default' %>
<% else %>
  <% if admin_signed_in? %>
    <%= link_to 'Add Address?', new_partner_address_path(@project), class: 'btn btn-default' %>
  <% else %>
    Address coming soon :\
  <% end %>
<% end %>