config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :donors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :charges

  resources :partners, only: [:index, :show]

  resources :locations, only: [:index, :show] do
    authenticate :admin do
      resources :projects, only: [:new, :create, :edit, :update, :destroy] do
        resources :campaigns, only: [:new, :create, :edit, :update, :destroy]
      end
    end

    resources :projects, only: [:index, :show] do
      resources :campaigns, only: [:index, :show]
    end
  end

  authenticate :admin do
    resources :locations, only: [:new, :create, :edit, :update, :destroy]
    resources :partners, only: [:new, :create, :edit, :update, :destroy]
  end

  # start polymorphic address/addressableassociations
  resources :partners do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :projects do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :donors do
    resources :addresses, only: [:new, :create, :edit, :update]
  end

  resources :admins do
    resources :addresses, only: [:new, :create, :edit, :update]
  end
  # end polymorphic address/addressable associations
end

app/models/location.rb
class Location < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  # must have a unique name and a slug
  validates_presence_of :name, :slug
  validates_uniqueness_of :name, :slug

  default_scope {order(name: :asc)}
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @locations = Location.all
  end

  def show
    @location = Location.friendly.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:notice] = 'Created location successfully'
      redirect_to locations_path
    else
      flash[:notice] = 'Save error, please try again'
      render :new
    end
  end

  def edit
    @location = Location.friendly.find(params[:id])
  end

  def update
    @location = Location.friendly.find(params[:id])
    if @location.update_attributes(location_params)
      flash[:notice] = 'Updated location successfully'
      redirect_to locations_path
    else
      flash[:notice] = 'Save error, please try again'
      render :edit
    end
  end

  def destroy
    Location.friendly.find(params[:id]).destroy
    flash[:success] = "Location deleted"
    redirect_to locations_path
  end

  private
    def location_params
      params.require(:location).permit(:name, :slug)
    end

end

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.submit 'Submit', class: "btn btn-default" %>
<% end %>

app/views/locations/edit.html.erb
<%= render partial: "form", locals: {location: @location} %>

app/views/locations/index.html.erb
<h1>Locations</h1>
<% if admin_signed_in? %>
  <% if @locations.present? %>
    <h2>Locations</h2>
    <ul>
    <% @locations.each do |location| %>
      <li><%= link_to location.name, location_path(location) %>
          <%= link_to 'Edit', edit_location_path(location) %>
          <%= link_to 'Delete', location, method: :delete,
              data: { confirm: "You want to delete this location?"} %>

          </li>
    <% end %>
    <ul>
  <% end %>
  <%= link_to 'Create location', new_location_path, class: 'btn btn-default' %>
<% else %>
  <% if @locations.present? %>
    <h2>Locations</h2>
    <ul>
    <% @locations.each do |location| %>
      <li><%= link_to location.name, location_path(location) %></li>
    <% end %>
    <ul>
  <% end %>
<% end %>

app/views/locations/new.html.erb
<%= render partial: "form", locals: {location: @location} %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<h2>Projects</h2>
<% if @location.projects.present? %>
  <% @location.projects.each do |project| %>
    <ul>
      <li><%= link_to project.name, location_projects_path(@location) %></li>
    </ul>
  <% end %>
<% end %>